### ISSUE TITLE
Show the full name and format of the generated file

### ISSUE THREAD

**Issue by SergeyVVVV** [toolzflow/app#10]
Now the name is cut because length is limited by 30 characters.

![image](https://github.com/user-attachments/assets/b9ead29e-294e-4559-9538-e19baa0c43f6)

The task is to Increase the limit.

**Comment by SergeyVVVV** [comment]
Fixed

**Comment by vood** [comment]
<img width="751" alt="image" src="https://github.com/user-attachments/assets/d2ee229c-8610-4c8b-b2b0-3da57fa9a955">
Updated the button, made it larger and nicely truncated if the name is too wide.
