### ISSUE TITLE
FTB Assistant is not assigned after Fork

### ISSUE THREAD

**Issue by spacemiidi** [toolzflow/app#2]
**Steps to reproduce:**

1. Create any app with Free Tool Builder (FTB)
2. Tap Fork

Current result: FTB assistant is not assigned in the new chat
Expected result: FTB assistant is assigned

![image](https://github.com/user-attachments/assets/2f31fffb-06c2-4a14-9a79-b38ec1203e92)

**Comment by vood** [comment]
fixed
