### ISSUE TITLE
Make adjustment to the banner "Make Your Version"

### ISSUE THREAD

**Issue by SergeyVVVV** [toolzflow/app#32]
Behaviour now:
The banner is displayed on a /free-tool page on our website.
A user taps on the banner and sees blurred ChatLabs interface with login window right inside the iFrame
This: 
a) doesn't look good 
b) doesn't work coz login window pop-ups again after the authentication and doesn't allow to use ChatLabs from a web page.

It can be fixed by opening a new tab when Make Your Version is tapped.

Examples:

Our page
![image](https://github.com/user-attachments/assets/9ab80d1b-fb05-4102-b98d-5bd7f691d398)

GetProg Hirsch Index
![image](https://github.com/user-attachments/assets/113694c5-3c73-4452-9082-a2cad730ea19)

**Comment by vood** [comment]
Fixed
