### ISSUE TITLE
The app refreshes on first use, then starts working correctly

### ISSUE THREAD

**Issue by SergeyVVVV** [toolzflow/app#5]
UPD. read the comment

Steps to reproduce:
1. Create fork chat
2. Continue to chat with AI asking for app changes

On the 2nd, 3rd and following changes 
- generated app works incorrectly only during the first use
- the app preview is refreshed
- then it works normally

Video: (промотать в середине, генерация долгая)
https://www.loom.com/share/d5d857cf4f0447b58fbfea4430dba071

**Comment by spacemiidi** [comment]
The issue is reproduced not in Fork chat only.
It is reproduced in any chat
