### ISSUE TITLE
Preview shows inaccurate UI

### ISSUE THREAD

**Issue by spacemiidi** [toolzflow/app#8]
**UI in preview**:
![image](https://github.com/user-attachments/assets/f87ef4e4-b964-436b-864f-b53749ca7410)

**Same UI on a web page:**
![image](https://github.com/user-attachments/assets/9ef8c09e-341d-4110-9c0a-6e1c54bf2c1a)

Link to app and chat
https://labs.writingmate.ai/share/0Y87
https://labs.writingmate.ai/chat?forkMessageId=8b353d1b-2bf3-4f0e-8268-0172b6e60e04&forkSequenceNo=0

**Comment by vood** [comment]
this is fixed. Both preview and shared app shows the same result. To fix the layout of the tabs, I recommend saying "use standard DaisyUI tabs"
